2023-08-22 12:17:14,963 INFO: Microblog startup [in C:\Users\Yash\PycharmProjects\microblog\app\__init__.py:27]
2023-08-24 13:27:16,952 INFO: Microblog startup [in C:\Users\Yash\PycharmProjects\microblog\app\__init__.py:27]
2023-08-24 13:29:06,671 INFO: Microblog startup [in C:\Users\Yash\PycharmProjects\microblog\app\__init__.py:27]
2023-08-24 13:29:28,038 INFO: Microblog startup [in C:\Users\Yash\PycharmProjects\microblog\app\__init__.py:27]
2023-08-24 13:29:31,084 ERROR: Exception on /user/Yash [GET] [in C:\Users\Yash\PycharmProjects\microblog\myenv\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\Yash\PycharmProjects\microblog\myenv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yash\PycharmProjects\microblog\myenv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yash\PycharmProjects\microblog\myenv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yash\PycharmProjects\microblog\myenv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yash\PycharmProjects\microblog\myenv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yash\PycharmProjects\microblog\app\routes.py", line 67, in user
    return render_template('user.html', user=user, posts=posts, form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yash\PycharmProjects\microblog\myenv\Lib\site-packages\flask\templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yash\PycharmProjects\microblog\myenv\Lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yash\PycharmProjects\microblog\myenv\Lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yash\PycharmProjects\microblog\myenv\Lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yash\PycharmProjects\microblog\myenv\Lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yash\PycharmProjects\microblog\myenv\Lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\Yash\PycharmProjects\microblog\myenv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Yash\PycharmProjects\microblog\app\templates\user.html", line 14, in template
    <form action="{{url_for('follow',username=username}}" method="post">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.TemplateSyntaxError: unexpected '}', expected ')'
